### ISSUE TITLE
[Accepted]: Command to make a Tab active / set focus

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#10]
In ribbon.js every Tab has a "Id".
How can I set/call a Tab to be active (JavaScript/jQuery-Command)?

**Comment by Kevin-De-Coninck** [comment]
This is not implemented yet, but should be possible in the future.
You should be able to set a tab and an icon as active or not.

This request has been accepted.

**Comment by Kevin-De-Coninck** [comment]
This issue has been resolved.
A JavaScript function has been created to change the active tab and can be called, for example on a button.

In order to make a tab have focus when clicking on a button, add this code in your HTML:

    <button onclick="$.fn.OfficeUI.setActiveTab('tabSendReceive');">Test</button>
