### ISSUE TITLE
Dynamic Tabs // or show() hide() for tabs

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#11]
For example, in Word2013 there will be a new tab, when you insert/edit a image or table.

![2015-01-20_11h19_22](https://cloud.githubusercontent.com/assets/5260747/5815482/39981858-a096-11e4-8af5-c0b4f81f85e1.png)

![2015-01-20_11h20_05](https://cloud.githubusercontent.com/assets/5260747/5815497/4cc628ac-a096-11e4-8cc6-498ad93e383a.png)

Will this be possible in OfficeUI too?
- I don't need the title over the tab-title ("Bildtools", "Tabellentools")
- I don't need the color

Why?
When a User open in my app a "Ticket", a new Tab will be shown called "Ticket" with menu-items like "Save"... - This menu-items make only sence, when the user is in the "Ticket"-Mode. When he leave the page, the tab as to hide.

So dynamical show and hide tabs will be great.

All "dynamic tab"-data into the ribbon.json too.
New attribute "show" for every tab-entry:
- true (default) - tab is vissible after OfficeUI loads
- false - tab is hidden

With a JavaScript-command it is possible to show() and hide() the tab.

**Comment by Kevin-De-Coninck** [comment]
Very good idea to implement this.
I'll look at this.

The feature has been accepted.

**Comment by Kevin-De-Coninck** [comment]
This feature has been implemented as from commit: 824e763ee7b9f96711babb41f7072e978ff0b540
