### ISSUE TITLE
[Workaround]: No Javascript function in sites from ApplicationMenu

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#13]
Download build 2015-01-22 15:50
No execute of this JavaScript-code when click at "Option" under the "FILE"-tab:
Add into OfficeUI.Beta\Resources\Data\Ribbon\ApplicationMenu\Options.html

```
<script>
console.log('test');
alert('test');
</script>
```

Build from 2015-01-19 
The JScode executes directly after index.html loads.
That was bad, because logoff.html execute some logout-stuff so the user is directly logout after login :-(

--

It is possible to load the page / run the JavaScript when the menu-item in the ApplicationMenu is clicked - like a normal page?
I thnig you load it into memory for the animation-effect.
In my case, a correct "page load function" is more important as the animation.
I don't like frames, but in HTML5 IFRAME is common supported - is this a option? I don't know...

**Comment by Kevin-De-Coninck** [comment]
This is basiclly how AngularJS does work and cannot really be changed.
Do you really need to place your code on the page 'Options.html'?

Maybe you can create a function and execute that when you click on the 'Options' menu item?

Kind regards

**Comment by doit-itservice** [comment]
Yes, I need JS - and not only for Options, sorry.

That sounds good! Of course I can put my JScode in a function per page and call the JSfunction from the menu-item of the ApplicationMenu.

Will it work like this
````
$(this).OfficeUI.bind("#applicationMenuOptions", "click", function() {
    // myFunction();
    // or
    // my JS-commands here
});
````

or you have to change something?

**Comment by Kevin-De-Coninck** [comment]
I believe that it should worlk like that without me to change anything.
Please give it a try and let me know the outcome.

If it's working fine, I can close this issue.


Kind regards,

**Comment by doit-itservice** [comment]
index.html

````
$( document ).ready(function() {
	console.log( "ready!" );
	 $.fn.OfficeUI.bind("#applicationMenuOptions", "click", function() {
		console.log('test');
		alert('test');
	});
});
````

and line ~ 180 add ID an onclick

````
<div onclick="console.log('click');" id="{{menuItem.Id}}" ng-if="menuItem.Seperator != 'True'">{{menuItem.Label}}</div>
````

"ready!" and "click" is logged into the console, but no 'test'....

-----------
2nd test:

in Options.html I add:
````
<script>
function test1()
{
	console.log('test1');
}
</script>
````

Change onclick from div to "test1();"
Console: ReferenceError: test1 is not defined

I can't find the content from
````
<application-menu-contents url="{{menuItem.Url}}" />
````
with the firefox inspector

Ideas?

**Comment by Kevin-De-Coninck** [comment]
Ok,

Can you give me a detailed explanation about what you want the application to do?
I'll see if I can test it myself then.


Kind regards

**Comment by doit-itservice** [comment]
Just a example from my logout-page

````
function ClearAuthentication(LogOffPage) 
{
	var IsInternetExplorer = false;    
	try
	{
		var agt=navigator.userAgent.toLowerCase();
		if (agt.indexOf("msie") != -1) { IsInternetExplorer = true; }
	}
	catch(e)
	{
		IsInternetExplorer = false;    
	};

	if (IsInternetExplorer) 
	{
		// Logoff Internet Explorer
		document.execCommand("ClearAuthenticationCache");
		//nix machen! //window.location = LogOffPage;
	}
	else 
	{
		// Logoff every other browsers
		$.ajax({
			username: 'unknown',
			password: 'WrongPassword',
			url: '/',		// Diese Seite muss STATUS 200 OK senden!!! (FireBug beachten)
			type: 'GET',
			beforeSend: function(xhr)
			{
				xhr.setRequestHeader("Authorization", "Basic AAAAAAAAAAAAAAAAAAA=");
			},
			error: function(err)
			{
				//nix machen! // window.location = LogOffPage;
			}
		});
	}
}

$(document).ready(function () 
{
	// Call Clear Authentication 
	ClearAuthentication("index.php"); 
}); 
````

-----
new test:
edit Options.html to

````
The contents of the menu entry 'Options' are displayed here.x hello
<script>
//console.log('test');
//alert('test');
function test1()
{
	console.log('test1');
}
</script>
<div onclick='test1();'>test</div>
````

Unknown function too :-(
Is AngularJS filtered any js code out?

http://stackoverflow.com/questions/15207788/calling-a-function-when-ng-repeat-has-finished
Different binding method for that?

**Comment by Kevin-De-Coninck** [comment]
Seems to be an issue with AngularJS.

I'm looking for a solution, but as a current workaround, define your function in the index.html page. That way you can call your script when clicking on the div just like you're doing right now.


Kind regards,
