### ISSUE TITLE
(low priority) - Umlauts in Tab-Title not working

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#14]
Hi Kevin,

Umlauts (ä ü ö ß) not working in the tab title (office.ui release 1).
In menu-items it works fine.

I use the html-code
````
ü --> &uuml;
````

I think the StringToUpper-Function breaks it, because &UUML; is not valid and so he output the text &UUML; instead of ü

Also tryed with UTF8 
````
&#220; 	and
&#x00DC;
````

![2015-02-10_14h59_52](https://cloud.githubusercontent.com/assets/5260747/6128484/95625512-b136-11e4-8ec9-05216b0db896.png)

**Comment by Kevin-De-Coninck** [comment]
Hello,

I do believe I have a solution for your problem.
I'll provide you with an update in a couple of hours.


Kind regards

**Comment by Kevin-De-Coninck** [comment]
This issue has now been resolved.

When I modify the Json file to contain the following contents:

    "Label": "File ä ü ö ß",

Then, the front-end is rendered as the following:

![image](https://cloud.githubusercontent.com/assets/3583827/6134032/8de073c8-b15e-11e4-9202-6b2ec3a857f3.png)

This fix can be found as from release 'Release_02'.


Kind regards.
