### ISSUE TITLE
(low priority) Minimize / collapse toggleRibbonState - no extend of content-area

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#15]
Hi Kevin,

when I minize the menu, it will only hide the ribbon-menu and will not extend the heigh of the content-area (officeui.beta release1)

![2015-02-10_15h32_23](https://cloud.githubusercontent.com/assets/5260747/6128909/50495c88-b13a-11e4-881c-8b809753046b.png)

**Comment by Kevin-De-Coninck** [comment]
Hello,

I do believe I have a solution for your problem.
I'll provide you with an update in a couple of hours.


Kind regards

**Comment by Kevin-De-Coninck** [comment]
This issue has been resolved in release 'Release_04'.


Kind regards.
