### ISSUE TITLE
No scrolling on applicationMenu-pages

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#16]
Hi,

there is no scrolling-availability on the applicationMenu-pages:

![2015-02-10_15h51_03](https://cloud.githubusercontent.com/assets/5260747/6129230/f1e984c6-b13c-11e4-991a-d9eb77e268be.png)

**Comment by Kevin-De-Coninck** [comment]
Hi there.

The solution seems a bit more difficult than I tought. This is because I want to scroll, but keep the title on the top of the page always visible.


Kind regards,

**Comment by doit-itservice** [comment]
forgot something: When on the main-page (not applicationMenu) a lot of content so the scrollbar is visible, the scrollbar is in applicationMenu visible too, but when you scroll, you scroll on the main-page behind the applicationMenu-Layer :-(

**Comment by Kevin-De-Coninck** [comment]
Hello, this issue is fixed right now on release 'Release_03'.
Could you check the other issue you're talking about?
If that issue is still persisting in the new release, please create a new issue.


Kind regards
