### ISSUE TITLE
R52 - Error 404 - Filetype .woff and .ttf

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#18]
Version R052 in Firefox:

![2015-03-03_13h01_03](https://cloud.githubusercontent.com/assets/5260747/6461966/6763b618-c1a5-11e4-9ee9-ccde408157f4.png)

Path to http://webserver/OfficeUI.Beta/Resources/fonts/fontawesome-webfont.woff is correct
I think I had to add the type as new MIME type in IIS, right?

Path to
http://webserver/OfficeUI.Beta/Resources/Stylesheets/External/fonts/fontawesome-webfont.ttf
is wrong!
C:\inetpub\wwwroot\OfficeUI.Beta\Resources\Stylesheets\External\fonts\ --> not exist
C:\inetpub\wwwroot\OfficeUI.Beta\Resources\Stylesheets\External\Font-Awesome\ --> here are only .css
fontawesome-webfont.ttf is under C:\inetpub\wwwroot\OfficeUI.Beta\Resources\fonts too!

Master-Question:
When the menu looks good without this files.... You can remove these files from the project?

Kind regards
Olli

**Comment by Kevin-De-Coninck** [comment]
This issue should be fixed in the latest checkin.
At least, I don't have the issue on my local computer.

Could you give it a try and if it's not working, please reopen this issue.
