### ISSUE TITLE
[very low prio] R52 - CSS - relative path incorrect

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#19]
Move the content from 
C:\inetpub\wwwroot\OfficeUI.Beta\
to
C:\inetpub\wwwroot\myapp\

Remove all "/OfficeUI.Beta/" (replace with "") from the sourcecode (index.html, *.js, *.css).
Click on the "FILE"-Tab - there is no arrow-back-image.

![2015-03-03_14h25_12](https://cloud.githubusercontent.com/assets/5260747/6463266/17aa4f5e-c1b1-11e4-8488-47d95305fbff.png)

In 
C:\inetpub\wwwroot\doit\Resources\Stylesheets\Styles\Turquoise\OfficeUI.Style.Turquoise.min.css

see URL in the screenshot - without slash
#navigation .back-arrow{background-image:url('Resources/Images/Ribbon/ApplicationMenu/NavigationArrow-Turquoise.png')}

see URL in the screenshot - with slash
#OfficeUI .application-contents #navigation .back-arrow:hover{background-image:url('/Resources/Images/Ribbon/ApplicationMenu/NavigationArrow-Turquoise_hover.png'

Okay... this works well:
#OfficeUI .application-contents #navigation .back-arrow:hover{background-image:url('../../../Images/Ribbon/ApplicationMenu/NavigationArrow-Turquoise_hover.png')}

Can you replace all path in the sourcecode - so OfficeUI is running without any project-directory-names in the sourcecode?

**Comment by Kevin-De-Coninck** [comment]
This issue has been fixed.
Now, all the OfficeUI.Beta paths have been removed from the source code.


Kind regards,
