### ISSUE TITLE
[ACCEPTED] Add url's in Json file for menu items and actions

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#3]
Hello Kevin,

here is my first feature request for OfficeUI.Beta.
How can I define a URL or JavaScript-function for a menu-item in the json-file?
Also, it should be possible to add actions behind an action on the ribbon.

Kind regards
Olli

**Comment by Kevin-De-Coninck** [comment]
Your issue is accepted and is being worked on.

**Comment by Kevin-De-Coninck** [comment]
Unfortunately, a JSON file cannot be used to pass functions or something else.
However, another solution has been implemented for this one.

In both, **application.json** or **ribbon.json** you can add 'Id' attributes to the icons.

That's being done like this:

    {
        "Id": "icoApplication",
        "Icon": "Resources/Images/Application/Application.png",
        "Alt": "Outlook"
    },

Then, in the html page itself, you can use the following code to attach event handlers to the various icons:

    $(this).OfficeUI.bind("#icoApplication", "click", function() {
        // code to add to the event here.
    });

The code above does add a click event on the icoApplication.

**Comment by doit-itservice** [comment]
x

**Comment by doit-itservice** [comment]
Hi,
thats good for a JavaScript-Events for a menu-button, but for normal URLs it's bad. Because
- more code
- everytime the page loads, have to register the event-handler for _every_ menu-item :-(

Whats about this:

New attribut in ribbon.json - e.g. "MyURL"
````
 "Id": "icoNewEmail",
"Resource": "Resources/Images/Ribbon/Tabs/Home/NewMailMessage.png",
"Legend": "New<br/> Email",
 "Tooltip": "<strong>New Item (Ctrl+N)</strong><p>Create a new item.</p>",
 "Type": "bIcon",
"MyURL": "http://www.google.de"
````

In Ribbon.html - Line 44 - before:
````
<div class="container area" ng-repeat="area in group.Areas">
<!-- The area to render a big icon. -->
<div class="container action" ng-repeat="action in area.Actions" ng-if="action.Type == 'bIcon'">
<div ngc-menu-holder="{menu: '#{{action.Id}}_menu'}" ngc-tooltip class="container icon big-icon"  ngc-dynamic-event-handling="action.Id" id="{{action.Id}}">
<img ng-src="{{action.Resource}}"/>
<div class="label" ng-bind-html="action |actionLegend"></div>
````

New:
````
<div class="container area" ng-repeat="area in group.Areas">
<!-- The area to render a big icon. -->
<div class="container action" ng-repeat="action in area.Actions" ng-if="action.Type == 'bIcon'">
<div ngc-menu-holder="{menu: '#{{action.Id}}_menu'}" ngc-tooltip class="container icon big-icon"  ngc-dynamic-event-handling="action.Id" id="{{action.Id}}">
<a ng-href="{{action.MyURL}}"><img ng-src="{{action.Resource}}"/>
<div class="label" ng-bind-html="action |actionLegend"></div></a>
````

What do you think?

**Comment by Kevin-De-Coninck** [comment]
I will implement this feature, however, I may call the property different.

**Comment by Kevin-De-Coninck** [comment]
This feature has been implemented.

Add a property 'Uri' to an action in the file 'ribbon.json' and when you click on the icon, you will be redirected to your given url.
