### ISSUE TITLE
Content for the "File" tab

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#4]
I think it is useful if the "File" tab displays not a ribbon menu, like the normal tabs. So it has a special function.

In Office 2013 a complete new page in fullscreen appears.
I prefer (for my web-app) the solution from Office 2007 for the File-tab - only a small menu-layer.
I want to put some entries like "preferences", "help", "logout" under this tab....

Like this: http://acidjs.wemakesites.net/pages/ribbon-bar-xml/demo/

**Comment by Kevin-De-Coninck** [comment]
I'm not too sure if I want to behave my ribbon like that.
I do think that it's better to provide a full area in which HTML can be showed, but the content that will be showed will be displayed in full screen, meaning the ribbon is not visible anymore.

**Comment by doit-itservice** [comment]
Hi Kevin,
ok, of course no problem.
It's only importent to give it some content/function, so I can use OfficeUI.Beta as soon as possible for my WebApp - I want to present it on the CeBIT in march ;-)

Later, when all other things are finished, somebody can eventual customize it.

**Comment by Kevin-De-Coninck** [comment]
Awesome, this means that my product is introduced as CeBIT.

**Comment by doit-itservice** [comment]
I would like to send you some information about it, but not here public on Github. Can you send me your eMail-address? contact@doit-ticket.de

**Comment by Kevin-De-Coninck** [comment]
Hello,

Just to give an impression of the contents behind the FILE tab.
I would like to give the user a lot of control to do this but keeping the Office style.

Therefore, the following approach has been selected:
Create a blue bar on the left with menu entries (stored in the ribbon.json) file and on the right, you'll have full control to render any HTML.

This will look something like:

![image](https://cloud.githubusercontent.com/assets/3583827/5712997/5a3c395c-9ab7-11e4-9ef2-11957f61d8ff.png)

There's still some work to be done, but estimated time to finish this should be the end of the week.

**Comment by doit-itservice** [comment]
:+1: 

I know, its no Office2013-Standard - but it is possible to add small icons on the menu entries too?

And it can be helpfully, when you config the width from the blue element, when the menu-text is too long (e.g. 1 more char = line-break = :-(  )

**Comment by Kevin-De-Coninck** [comment]
Do you mean the menu entries in the blue area? 
I can add it but I don't like it. 

Why would you like to see this since it's no default behaviour?

**Comment by doit-itservice** [comment]
>Do you mean the menu entries in the blue area? 

yes

>Why would you like to see this since it's no default behaviour? 

Icons can support the user, because a icon is optical better then only text.
I want just try it, maybe it is no good idea - we will see...

**Comment by Kevin-De-Coninck** [comment]
Menu is ready (at least a very first version, you can give it a try, but some other things are broken. I'll fix them in a next version - and will also cleanup the HTML a bit).

**Comment by doit-itservice** [comment]
Don't forget the "back"-Button :-)

**Comment by Kevin-De-Coninck** [comment]
This feature is implemented right now.
Please check the newly released version.
