### ISSUE TITLE
[Accepted] (low priority) Provide configuration to "fixed position" for ribbon menu

### ISSUE THREAD

**Issue by doit-itservice** [Kevin-De-Coninck/OfficeUI.Beta#6]
Hi,
please provide to choose if the menu a normal html-element or a element with a fixed position, this means, when scrolling the page, the ribbon menu is always at the top available.
Like this: http://okgodoit.com/ribbon/  (make the browser-window smaller for scrolling)

**Comment by Kevin-De-Coninck** [comment]
The issue is fixed.

The ribbon is always positioned on top op of the page, event when scrolling.
Then content beneath the ribbon appears to be scrolling behind the ribbon.
